name: Update Data and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  schedule:
    # S'exécute automatiquement toutes les 12 heures
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch MAL Data
        env:
          MAL_CLIENT_ID: ${{ secrets.MAL_CLIENT_ID }}
        run: python fetch_data.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
